require 'test_helper'

class PagesControllerTest < ActionDispatch::IntegrationTest
  

  
  # Automatically generated by Rails. However, I put this page as my root. So it fails. 
  test "should get home" do
    get root_path
    assert_response :success
    assert_select "title", "Home | CourseBuddies"
  end

  test "should get about" do
    get about_path
    assert_response :success
    assert_select "title", "About | CourseBuddies"
  end
  


end
